version: '3.8'
services:
  eureka:
    image: alexb-io/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_SERVER_PORT=8761
    depends_on:
      - gateway
      - order-service
    networks:
      - microservices

  gateway:
    image: alexb-io/gateway-server:latest
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka
    networks:
      - microservices

  order-service:
    image: alexb-io/order-service:latest
    container_name: order-service
    ports:
      - "8060:8060"
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka
    networks:
      - microservices

#  db:
#    image: mysql:5.7
#    environment:
#      MYSQL_ROOT_PASSWORD: example
#      MYSQL_DATABASE: mydb
#    ports:
#      - "3306:3306"
#    networks:
#      - microservices

networks:
  microservices:
    driver: bridge
