version: '3.8'
services:
  eureka:
    image: alexb-io/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_SERVER_PORT=8761
    depends_on:
      - gateway
      - order-service
    networks:
      - microservices

  gateway:
    image: alexb-io/gateway-server:latest
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVER_URI=http://eureka-server:8761/eureka
    networks:
      - microservices

  order-service:
    image: alexb-io/order-service:latest
    container_name: order-service
    ports:
      - "8060:8060"
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-container:3306/ecommerce_db
    depends_on:
      - db
      - user-service
      - product-service
    networks:
      - microservices

  product-service:
    image: alexb-io/product-service:latest
    container_name: product-service
    ports:
      - "8061:8061"
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-container:3306/ecommerce_db
    depends_on:
      - db
      - user-service
    networks:
      - microservices

  user-service:
    image: alexb-io/user-service:latest
    container_name: user-service
    ports:
      - "8062:8062"
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-container:3306/ecommerce_db
    depends_on:
      - db
    networks:
      - microservices

  db:
    image: mysql:5.7
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD: ecommerce_db
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3306:3306"
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
