spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/rest/api/order/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
