spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/api/orders/**
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/users/**
        - id: product
          uri: lb://product
          predicates:
            - Path=/api/products/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
